Remove WSC plugin from Standard and Full presets
ckeditor/ckeditor4-presets pull request #55
Opened 2021-01-05 16:07 UTC by Dumluregn

As stated in the issue, plugin is actually still in presets, but excluded in config using `removePlugins` property. It works flawlessly - the only difference is that the `Check spelling` option doesn't appear in the context menu after clicking Spell Checker toolbar button.

I've also done a research on how will that behave in the docs. Samples use the standard preset with the config from this repo by default meaning the WSC plugin will be automatically disabled there too. However, if the sample overrides the `removePlugins` property, the WSC plugin will be included again (as the default config is ignored then). 
On one hand that's good, because no changes in the [Spellchecker](https://ckeditor.com/docs/ckeditor4/latest/examples/spellchecker.html) sample are necessary. OTOH even though we disable WSC here, it will still be present e.g. in [inline editor sample](https://ckeditor.com/docs/ckeditor4/latest/examples/inline.html) as it uses custom `removePlugins` (removing `stylesCombo` plugin). So we may either live with it, or create a separate PR in docs adding the WSC to each `removePlugins` property...

Closes #53.

2021-01-07 09:39 UTC, f1ames requested changes
> I've also done a research on how will that behave in the docs. Samples use the standard preset with the config from this repo by default meaning the WSC plugin will be automatically disabled there too. However, if the sample overrides the `removePlugins` property, the WSC plugin will be included again (as the default config is ignored then).  
> On one hand that's good, because no changes in the [Spellchecker](https://ckeditor.com/docs/ckeditor4/latest/examples/spellchecker.html) sample are necessary. OTOH even though we disable WSC here, it will still be present e.g. in [inline editor sample](https://ckeditor.com/docs/ckeditor4/latest/examples/inline.html) as it uses custom `removePlugins` (removing `stylesCombo` plugin). So we may either live with it, or create a separate PR in docs adding the WSC to each `removePlugins` property...

I would say you took the most valid and proper approach to solve this issue, however I'm not entirely sure if that's exactly what we need here :wink::exploding\_head:

Our docs samples are the smallest problem here because we have full control over it. It's more about telling users that plugin EOL is coming. The intention here is to have similar situation with WSC plugin in `standard`/`full` presets as we have with all optional plugins in `standar-all` and `full-all` presets. Such plugins are not active by default but can be simply added by changing `plugins` config or adding `extraPlugins` config option.

By removing WSC plugin via `removePlugins` we have few issues:

1.  If someone is already using this config option, default value will be override and will have no effect as you mentioned in above.
2.  The `removePlugins` option overrides `plugins` and `extraPlugins` options (see [`core/editor.js`](https://github.com/ckeditor/ckeditor4/blob/5380706bb4ceb6092dadb2b7067d6c14efec6b26/core/editor.js#L501-L512)), so the only way to enable it is to remove/overrides default `removePlugins` value.
3.  The plugin code is still included in main `ckeditor.js` which makes the file even though this code is not used by default.

So I guess to solve this specific issue and satisfy the above we will need to do a little magic - remove `wsc` plugin entirely from `*-build-config.js` and then copy it to build output `plugins` directory as a late build process step. Yes... custom hardcoded logic... :see\_no\_evil::speak\_no\_evil:  Feel free to drop in any better ideas we may discuss and consider changing the approach here.

2021-01-12 14:10 UTC, Dumluregn commented
Important - this PR should be merged after a new CKBuilder version is released. It requires bumping CKBuilder version in `build.sh` file first - to `2.3.3` or `2.4.0`, depending on which number will be chosen.

2021-01-13 14:24 UTC, f1ames approved these changes
Checked together with `ckbuilder` PR (see https://github.com/ckeditor/ckbuilder/pull/30#pullrequestreview-567236978). It works es expected, the plugin files/structure is identical when added to preset through `all` and `r` flag and that was what we were aiming for :+1: 

This PR will be merged after https://github.com/ckeditor/ckbuilder/pull/30 is concluded and new  `ckbuilder` version released.

2021-01-14 14:26 UTC, f1ames commented
Updated builder version in `build.sh` so when new version is out we can restart CI and if it's green, merge this PR.

2021-01-18 15:49 UTC, f1ames commented
Rebased onto latest `master`.

Let's wait for the CI and we will be good to go :+1:

2021-01-19 10:00 UTC, Dumluregn commented
CI is red because of known `exportpdf` issue, so I think we are ready for merge 🎉

2021-01-19 11:27 UTC, merged